apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: taiwrash-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiwrash-portfolio
  template:
    metadata:
      labels:
        app: taiwrash-portfolio
    spec:
      containers:
        - name: portfolio
          image: taiwrash/portfolio:latest
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          # Optionally, you can set resource requests/limits:
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: taiwrash-portfolio
spec:
  selector:
    app: taiwrash-portfolio
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
